### PR TITLE
fix: enum of not connect for mihomo

### LINKED ISSUE #867: 测速失败节点延迟显示0ms
如图 metacubexd版本为1.143.1 meta内核版本为alpha-4051ea5

### PR DESCRIPTION
**Pull request by YetAnotherZephyruso**
It seems the mihomo will return 0 rather than -1 of latency when latency test is failed, and sing-box will return nothing. try fix #867 since i don't have a mihomo config, please try to see if it works @kunish

### CODE REVIEW

**Comment by YetAnotherZephyruso** [comment]
replace all latencyMap()[name] with a get base on getNowProxyNodeName so we can get the real latency

**Comment by YetAnotherZephyruso** [comment]
Change the size of the input to 'sm' to balance the visual issue of having a smaller left side and a larger right side. This change involves the rules, connetions, and logs. The input on the config page was not modified because it is the main content and needs to be more prominent, while in the aforementioned three pages, the input serves more as a supporting role. The background color of the button was changed to better integrate with the input.
image

**Comment by kunish** [comment]
> It seems the mihomo will return 0 rather than -1 of latency when latency test is failed, and sing-box will return nothing. try fix #867 since i don't have a mihomo config, please try to see if it works @kunish

It works as expected now.

**Comment by kunish** [comment]
image

Found a subtle issue, the client ip selector text gets truncated, i believe this comes from previous PR (Quick Filter)

**Comment by YetAnotherZephyruso** [comment]
> image
> Found a subtle issue, the client ip selector text gets truncated, i believe this comes from previous PR (Quick Filter)

I'll see what i can do

**Comment by YetAnotherZephyruso** [comment]
image
image

How about this one? I have to make the quick filter in the middle of input and select and remove the primary color of select to avoid a sense of color disconnection

**Comment by YetAnotherZephyruso** [comment]
image
I found there is a lagger padding than other tab, And i set a px-2 for this tab too

**Comment by YetAnotherZephyruso** [comment]
image
Minor fix for logo text

**Comment by kunish** [comment]
Nice catch

**Comment by kunish** [comment]
Anything else?

**Comment by YetAnotherZephyruso** [comment]
> Anything else?

No i don't have anything else

**Comment by YetAnotherZephyruso** [comment]
I think #650 #634 #574 #476 #475 #450 is fixed now and we can close these issues @kunish

**Pull request merged**
