### PR TITLE
fix(overview): error when reading length

### PR DESCRIPTION
**Pull request by nb5p**

### CODE REVIEW

**Comment by kunish** [comment]
Is this business still relevant?

**Comment by nb5p** [comment]
> Is this business still relevant?

I don't know. I have noticed that the connections variable is null when the overview page is blank. This indicates that the clash backend may return a null value in certain situations.

**Comment by kunish** [comment]
Fix the type definition then, we can merge this

**Comment by nb5p** [comment]
I will take care of it later.

**Pull request merged**
