### PR TITLE
feat: quick filter for connections

### PR DESCRIPTION
**Pull request by YetAnotherZephyruso**
image
image
A quick filter option that filters connections's chain using regex, allowing router users to quickly filter out unwanted direct connection or dns-out connection for sing-box users with one click, the regex can be customize

### CODE REVIEW

**Comment by YetAnotherZephyruso** [comment]
And pre-sort connections with id to get a more stable table rows when sort with other key

**Comment by YetAnotherZephyruso** [comment]
Should i split these with three different pr or just stay with one?

**Comment by YetAnotherZephyruso** [comment]
Make persisted for collapse map

**Comment by kunish** [comment]
Great addition to the features, great idea, nice work!

**Pull request merged**
